import type {HistoricalEntry} from "$lib/utils";
import autoGeneratedOldShows from "../scripts/old-history-generator/output.json" assert { type: "json" };

// Insert overrides here. Any overrides will replace auto-generated entries.
const overrides: HistoricalEntry[] = [];



const historyBuilding: HistoricalEntry[] = autoGeneratedOldShows as HistoricalEntry[];
for (let historicalEntry of historyBuilding) {
    for (const override of overrides) {
        if(override.name == historicalEntry.name) {
            historicalEntry = override;
            break;
        }
    }
}
export const history: HistoricalEntry[] = historyBuilding;