import type {HistoricalEntry} from "$lib/utils";
import autoGeneratedOldShows from "../scripts/old-history-generator/output.json" assert { type: "json" };

// Insert overrides here. Any overrides will replace auto-generated entries.
const overrides: HistoricalEntry[] = [
    {
        "name": "2021/09/17",
        "metadata": {
            "preShowStart": "2021-09-18T01:35:12.000Z",
            "mainShowStart": "2021-09-18T01:44:43Z",
            "showEnd": "2021-09-18T03:16:27Z",
            "title": "Did Apple Just Prove the iPhone Could be Cheaper?",
            "vods": {
                "floatplane": "WHfZYknvam",
                "youtube": "jPidIspifRM"
            },
            "snippet": {
                "publishedAt": "2021-09-18T03:25:51Z",
                "channelId": "UCXuqSBlHAE6Xw-yeJA0Tunw",
                "title": "Did Apple Just Prove the iPhone Could be Cheaper? - WAN Show September 17, 2021",
                "description": "Save 10% at Ridge Wallet with offer code WAN at https://www.ridge.com/WAN\n\nHead over to joinhoney.com/linus and start saving today\n\nBuy a Seasonic Ultra Titanium PSU\nOn Amazon: https://geni.us/q4lnefC\nOn NewEgg: https://lmg.gg/8KV3S\n\nPodcast Download: https://anchor.fm/thewanshowpodcast/episodes/Did-Apple-Just-Prove-the-iPhone-Could-be-Cheaper----WAN-Show-September-17--2021-e17k9te\n\nCheck out our other Podcasts:\nCarpool Critics Movie Podcast: https://www.youtube.com/channel/UCt-oJR5teQIjOAxCmIQvcgA\n\nTimestamps (Courtesy of NoKi1119)\n[0:00] Chapters.\n[1:31] Intro.\n[1:56] Colton blames Geoff for no sponsors.\n[4:06] Topic #1: Apple's annual September event.\n    5:57 A15 specs & Geekbench result.\n    9:35 ProRes enabled on iPhone 13 Pro.\n    13:56 iPhone & iPad Mini improvements.\n    15:22 Lightning vs USB C.\n    17:36 iPad Mini is a bigger iPhone.\n    20:33 iPad 9th Gen & Apple Watch Series 7.\n    21:34 Apple sued for \"Sherlocking\" apps.\n    29:34 Issues with OLED displays on Windows.\n[36:26] Sponsors.\n    36:40 Seasonic's Ultra Titanium PSUs.\n    37:51 Honey Promo Codes.\n    38:50 Ridge Wallet.\n[40:04] Topic #2: LG 325-Inch 8K \"Whole Wall\" TV.\n    41:32 DVLED Home Theater Cinema TV.\n    44:20 LG's peak watt usage & other specs.\n    49:38 Different modules for TV models.\n    55:14 Responding to chat regarding purchases.\n    1:00:20 AirBnB & other leisure renting.\n[1:04:55] Topic #3: FloatPlane early-access REMOVED.\n[1:07:07] LTTstore new merch.\n[1:08:18] Topic #4: Sennheiser's new HD 8xx.\n[1:11:38] Superchats & discussing Framework.\n[1:30:35] Wrapping up.\n[1:31:23] Outro.",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/jPidIspifRM/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/jPidIspifRM/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/jPidIspifRM/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    },
                    "standard": {
                        "url": "https://i.ytimg.com/vi/jPidIspifRM/sddefault.jpg",
                        "width": 640,
                        "height": 480
                    }
                },
                "channelTitle": "Linus Tech Tips",
                "tags": [
                    "pcmr",
                    "building",
                    "competition",
                    "gamers",
                    "how to",
                    "review",
                    "intel",
                    "amd",
                    "cpu",
                    "gpu",
                    "gaming"
                ],
                "categoryId": "28"
            }
        }
    },
    {
        "name": "2021/09/10",
        "metadata": {
            "preShowStart": "2021-09-11T01:31:00.000Z",
            "mainShowStart": "2021-09-11T01:34:29Z",
            "showEnd": "2021-09-11T02:54:41Z",
            "title": "Apple WON... but also Lost",
            "vods": {
                "floatplane": "9uLS5T4TNV",
                "youtube": "1VW0uaoN5Yc"
            },
            "snippet": {
                "publishedAt": "2021-09-11T03:05:42Z",
                "channelId": "UCXuqSBlHAE6Xw-yeJA0Tunw",
                "title": "Apple WON... but also Lost - WAN Show September 10, 2021",
                "description": "Try JumpCloud for free at https://cloud.jumpcloud.com/WANshow\n\nHelp your IT team take care of support, maintenance, and security for Enterprise Linux systems with TuxCare at https://hubs.ly/H0WRkfb0\n\nTry FreshBooks free, for 30 days, no credit card required at https://www.freshbooks.com/wan\n\nPodcast Download: https://anchor.fm/thewanshowpodcast/episodes/Apple-WON----but-also-Lost---WAN-Show-September-10--2021-e17a83g\n\nCheck out our other Podcasts:\nCarpool Critics Movie Podcast: https://www.youtube.com/channel/UCt-oJR5teQIjOAxCmIQvcgA\n\nTimestamps (courtesy of NoKi1119)\n\n[0:00] Chapters.\n[1:20] Intro.\n[2:10] Topic #1: Apple VS Epic suit is FINALLY over.\n    6:26 Tim Sweeney's reaction.\n    9:37 Epic's developer Apple account.\n    11:02 Effects on the developers and consumers.\n[17:26] Topic #2: ProtonMail is not really private.\n    23:10 Changes and securing your mail.\n[25:30] Sponsors.\n    25:34 Jumpcloud Cloud Active Directory.\n    28:21 TuxCare Open Source Linux Support.\n    29:21 Freshbooks Accounting.\n[30:36] Topic #3: The Matrix Resurrections Trailer.\n    34:05 Linus criticizes the movie, genre & its' MMO.\n    40:51 PS Showcase & Star Wars remake.\n    43:12 Grand Theft Auto 5 Enhanced Edition delayed.\n[44:31] Topic #4: Facebook smart glasses.\n    46:02 Pricing and specs.\n    49:19 Better POV videos.\n    51:27 Comparing to Google Glass.\n[53:28] Topic #5: Valorant anti-cheat & TPM 2.0.\n[1:04:47] TechIngredient's thermal paste.\n[1:05:36] LTTstore new merch.\n[1:07:35] Superchats.\n[1:19:06] Wrapping up.\n[1:19:51] Outro.",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/1VW0uaoN5Yc/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/1VW0uaoN5Yc/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/1VW0uaoN5Yc/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    },
                    "standard": {
                        "url": "https://i.ytimg.com/vi/1VW0uaoN5Yc/sddefault.jpg",
                        "width": 640,
                        "height": 480
                    }
                },
                "channelTitle": "Linus Tech Tips",
                "tags": [
                    "pcmr",
                    "building",
                    "competition",
                    "gamers",
                    "how to",
                    "review",
                    "intel",
                    "amd",
                    "cpu",
                    "gpu",
                    "gaming"
                ],
                "categoryId": "28"
            }
        }
    }
];



const historyBuilding: HistoricalEntry[] = autoGeneratedOldShows as HistoricalEntry[];
for (let i = 0; i < historyBuilding.length; i++) {
    const historicalEntry = historyBuilding[i];
    for (const override of overrides) {
        if(override.name == historicalEntry.name) {
            console.debug("Override found for ", override.name);
            historyBuilding[i] = override;
            break;
        }
    }
}
export const history: HistoricalEntry[] = historyBuilding;