import type {HistoricalEntry} from "$lib/utils";
import autoGeneratedOldShows from "../scripts/old-history-generator/output.json" assert { type: "json" };

// Insert overrides here. Any overrides will replace auto-generated entries.
const overrides: HistoricalEntry[] = [
    {
        "name": "2021/09/10",
        "metadata": {
            "preShowStart": "2021-09-11T01:31:00.000Z",
            "mainShowStart": "2021-09-11T01:34:29Z",
            "showEnd": "2021-09-11T02:54:41Z",
            "title": "Apple WON... but also Lost",
            "vods": {
                "floatplane": "9uLS5T4TNV",
                "youtube": "1VW0uaoN5Yc"
            },
            "snippet": {
                "publishedAt": "2021-09-11T03:05:42Z",
                "channelId": "UCXuqSBlHAE6Xw-yeJA0Tunw",
                "title": "Apple WON... but also Lost - WAN Show September 10, 2021",
                "description": "Try JumpCloud for free at https://cloud.jumpcloud.com/WANshow\n\nHelp your IT team take care of support, maintenance, and security for Enterprise Linux systems with TuxCare at https://hubs.ly/H0WRkfb0\n\nTry FreshBooks free, for 30 days, no credit card required at https://www.freshbooks.com/wan\n\nPodcast Download: https://anchor.fm/thewanshowpodcast/episodes/Apple-WON----but-also-Lost---WAN-Show-September-10--2021-e17a83g\n\nCheck out our other Podcasts:\nCarpool Critics Movie Podcast: https://www.youtube.com/channel/UCt-oJR5teQIjOAxCmIQvcgA\n\nTimestamps (courtesy of NoKi1119)\n\n[0:00] Chapters.\n[1:20] Intro.\n[2:10] Topic #1: Apple VS Epic suit is FINALLY over.\n    6:26 Tim Sweeney's reaction.\n    9:37 Epic's developer Apple account.\n    11:02 Effects on the developers and consumers.\n[17:26] Topic #2: ProtonMail is not really private.\n    23:10 Changes and securing your mail.\n[25:30] Sponsors.\n    25:34 Jumpcloud Cloud Active Directory.\n    28:21 TuxCare Open Source Linux Support.\n    29:21 Freshbooks Accounting.\n[30:36] Topic #3: The Matrix Resurrections Trailer.\n    34:05 Linus criticizes the movie, genre & its' MMO.\n    40:51 PS Showcase & Star Wars remake.\n    43:12 Grand Theft Auto 5 Enhanced Edition delayed.\n[44:31] Topic #4: Facebook smart glasses.\n    46:02 Pricing and specs.\n    49:19 Better POV videos.\n    51:27 Comparing to Google Glass.\n[53:28] Topic #5: Valorant anti-cheat & TPM 2.0.\n[1:04:47] TechIngredient's thermal paste.\n[1:05:36] LTTstore new merch.\n[1:07:35] Superchats.\n[1:19:06] Wrapping up.\n[1:19:51] Outro.",
                "thumbnails": {
                    "default": {
                        "url": "https://i.ytimg.com/vi/1VW0uaoN5Yc/default.jpg",
                        "width": 120,
                        "height": 90
                    },
                    "medium": {
                        "url": "https://i.ytimg.com/vi/1VW0uaoN5Yc/mqdefault.jpg",
                        "width": 320,
                        "height": 180
                    },
                    "high": {
                        "url": "https://i.ytimg.com/vi/1VW0uaoN5Yc/hqdefault.jpg",
                        "width": 480,
                        "height": 360
                    },
                    "standard": {
                        "url": "https://i.ytimg.com/vi/1VW0uaoN5Yc/sddefault.jpg",
                        "width": 640,
                        "height": 480
                    }
                },
                "channelTitle": "Linus Tech Tips",
                "tags": [
                    "pcmr",
                    "building",
                    "competition",
                    "gamers",
                    "how to",
                    "review",
                    "intel",
                    "amd",
                    "cpu",
                    "gpu",
                    "gaming"
                ],
                "categoryId": "28"
            }
        }
    }
];



const historyBuilding: HistoricalEntry[] = autoGeneratedOldShows as HistoricalEntry[];
for (let i = 0; i < historyBuilding.length; i++) {
    const historicalEntry = historyBuilding[i];
    for (const override of overrides) {
        if(override.name == historicalEntry.name) {
            console.debug("Override found for ", override.name);
            historyBuilding[i] = override;
            break;
        }
    }
}
export const history: HistoricalEntry[] = historyBuilding;